-- Create Table

-- DATE FORMAT YY/MM/DD
-- TIME FORMAT HH:MM:SS

CREATE TABLE retail_sales_db
		(
					transaction_id INT PRIMARY KEY,
					sale_date DATE,
					sale_time TIME,
					customer_id INT,
					gender VARCHAR(10),
					age INT,
					category VARCHAR(20),
					quantity INT,
					price_per_unit FLOAT,
					cogs FLOAT,
					total_sale FLOAT
		);

SELECT * FROM retail_sales_db
LIMIT 20;


SELECT 
	COUNT(*) 
FROM retail_sales_db;

-- DATA CLEANING:
-- CHECKING FOR NULL VALUES:

-- NULL VALUES IN TRANSACTION ID:
SELECT * 
FROM retail_sales_db
WHERE transaction_id IS NULL;

-- NULL VALUES IN SALE_DATE:
SELECT * 
FROM retail_sales_db
WHERE sale_date IS NULL;

-- NULL VALUES IN SALE TIME:
SELECT * 
FROM retail_sales_db
WHERE sale_time IS NULL;


-- NULL VALUES IN CUSTOMER ID:
SELECT * 
FROM retail_sales_db
WHERE customer_id IS NULL;


-- NULL VALUES IN GENDER:
SELECT * 
FROM retail_sales_db
WHERE gender IS NULL;


-- NULL VALUES IN AGE:
SELECT COUNT(*) 
FROM retail_sales_db
WHERE age IS NULL;


-- NULL VALUES IN CATEGORY:
SELECT * 
FROM retail_sales_db
WHERE category IS NULL;

	
-- NULL VALUES IN QUANTITY:
SELECT count(*)
FROM retail_sales_db
WHERE quantity IS NULL;


-- NULL VALUES IN PRICE PER UNIT:
SELECT COUNT(*) 
FROM retail_sales_db
WHERE price_per_unit IS NULL;


-- NULL VALUES IN COGS:
SELECT COUNT(*)
FROM retail_sales_db
WHERE COGS IS NULL;


-- NULL VALUES IN TOTAL SALES:
SELECT COUNT(*) 
FROM RETAIL_SALES_DB
WHERE TOTAL_SALE IS NULL;

-- OR:
SELECT COUNT(*) 
FROM RETAIL_SALES_DB
WHERE
	transaction_id IS NULL
	OR
	sale_date IS NULL
	OR
	sale_time IS NULL
	OR
	customer_id IS NULL
	OR
	gender IS NULL
	OR
	AGE IS NULL
	OR
	CATEGORY IS NULL
	OR
	QUANTITY IS NULL
	OR
	PRICE_PER_UNIT IS NULL
	OR
	COGS IS NULL
	OR
	TOTAL_SALE IS NULL;

-- Deleting NULL Values:
DELETE FROM RETAIL_SALES_DB
WHERE
	transaction_id IS NULL
	OR
	sale_date IS NULL
	OR
	sale_time IS NULL
	OR
	customer_id IS NULL
	OR
	gender IS NULL
	OR
	AGE IS NULL
	OR
	CATEGORY IS NULL
	OR
	QUANTITY IS NULL
	OR
	PRICE_PER_UNIT IS NULL
	OR
	COGS IS NULL
	OR
	TOTAL_SALE IS NULL;

-- TOTAL ROWS WE HAVE:
SELECT COUNT(*)
FROM RETAIL_SALES_DB;



-- DATA EXPLORATIONS:

-- TOTAL SALES WE HAVE DONE SO FAR:
SELECT COUNT(*) AS TOTAL_SALES
FROM RETAIL_SALES_DB;

-- CHECK FOR TOTAL MALES AND FEMALES:
SELECT 
	COUNT(gender) AS MALES_AND_FEMALES
FROM retail_sales_db
GROUP BY(gender);


--CHECK HOW MANY UNIQUE CUSTOMERS THERE ARE:
SELECT 
	COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM retail_sales_db;

-- CHECKING HOW MANY CATEGORIES WE HAVE:
SELECT 
	category
FROM retail_sales_db
GROUP BY(category);
--or
SELECT 
	DISTINCT CATEGORY
FROM RETAIL_SALES_DB;

-- AGE GROUPING
SELECT AGE, COUNT(AGE) AS NO_OF_PERSONS
FROM RETAIL_SALES_DB
GROUP BY AGE
ORDER BY COUNT(AGE) DESC


-- DATA ANALYSIS OR BUSINESS KEY PROBLEMS & ANSWERS:

-- Q.1 W.A SQL QUERY TO RETRIVE ALL THE COLUMNS FOR SALES MADE ON "2022-11-22":
SELECT * 
FROM RETAIL_SALES_DB
WHERE SALE_DATE = '2022-11-22'
ORDER BY SALE_TIME;

-- Q.2 W.A SQL QUERY TO RETRIVE ALL TRANSACTIONS WHERE THE CATEGORY IS "CLOTHING" AND THE QUANTITY SOLD 
--IS MORE THAN 10 IN THE MONTH OF NOVEMBER 2022
SELECT *
FROM RETAIL_SALES_DB
WHERE 
	category = 'Clothing' 
	AND quantity > 3 AND 
	sale_date BETWEEN '2022-11-01' AND '2022-11-30'
ORDER BY SALE_DATE;

-- Q.3 W.A SQL QUERY TO CALCULATE THE TOTAL SALES FOR EACH CATEGORY:
SELECT 
	CATEGORY,
	COUNT(CATEGORY) AS TOTAL_NO_OF_SALES,
	SUM(TOTAL_SALE) AS TOTAL_SUM_OF_SALES
FROM RETAIL_SALES_DB
GROUP BY CATEGORY;


-- Q.4 W.A SQL QUERY TO FIND THE AVERAGE AGE OF CUSTOMERS WHO 
-- PURCHASED ITEMS FROM THE "BEAUTY" CATEGORY
SELECT
	CATEGORY,
	COUNT(CATEGORY) AS NO_OF_PERSONS,
	ROUND(AVG(AGE),2) AS AVERAGE_AGE
FROM RETAIL_SALES_DB
GROUP BY CATEGORY
HAVING CATEGORY = 'Beauty'
-- OR
SELECT
	ROUND(AVG(AGE),2) AS AVERAGE_AGE
FROM RETAIL_SALES_DB
WHERE CATEGORY = 'Beauty'

-- Q.5 W.A SQL QUERY TO FIND ALL TRANSACTIONS WHERE THE TOTAL SALES IS GREATER THAN 1000
SELECT *
FROM RETAIL_SALES_DB
WHERE TOTAL_SALE>1000
ORDER BY SALE_DATE,SALE_TIME;

-- Q.6 W.A SQL QUERY TO FIND THE TOTAL TRANSACTIONS(TRANSACTION_ID) 
-- MADE BY EACH GENDER IN EACH CATEGORY
SELECT 
	CATEGORY,
	GENDER,
	COUNT(TRANSACTION_ID)
FROM RETAIL_SALES_DB
GROUP BY CATEGORY, GENDER
ORDER  BY CATEGORY

-- Q.7. W.A SQL QUERY TO CALCULATE THE AVERAGE SALE FOR EACH MONTH. 
-- FIND OUT THE BEST-SELLING MONTH IN EACH YEAR
SELECT 
		EXTRACT(YEAR FROM SALE_DATE) AS YEAR,
		EXTRACT(MONTH FROM SALE_DATE) AS MONTH,
		AVG(TOTAL_SALE) AS AVERAGE
FROM RETAIL_SALES_DB
GROUP BY 1,2
ORDER BY AVG(TOTAL_SALE) DESC
LIMIT 2;
-- OR 
SELECT 
	YEAR,
	MONTH,
	AVG_SALE
FROM
	(SELECT 
		EXTRACT(YEAR FROM SALE_DATE) AS YEAR,
		EXTRACT(MONTH FROM SALE_DATE) AS MONTH,
		AVG(TOTAL_SALE) AS AVG_SALE,
		RANK() OVER(PARTITION BY EXTRACT(YEAR FROM SALE_DATE) ORDER BY AVG(TOTAL_SALE) DESC) AS RANK_NO
	FROM RETAIL_SALES_DB
	GROUP BY 1,2) AS T1
WHERE RANK_NO = 1

-- Q.8 W.A SQL QUERY TO FIND TOP 5 CUSTOMERS BASED ON THE HIGHEST TOTAL SALES:
SELECT 
	CUSTOMER_ID,
	SUM(TOTAL_SALE) AS TOTAL_SALES
FROM RETAIL_SALES_DB
GROUP BY CUSTOMER_ID
ORDER BY SUM(TOTAL_SALE) DESC
LIMIT 5;

-- Q.9 W.A SQL QUERY TO FIND THE NUMBER OF UNIQUE CUSTOMERS WHO PURCHASED ITEMS FROM EACH CATEGORY
SELECT 
	CATEGORY,
	COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM RETAIL_SALES_DB
GROUP BY CATEGORY
ORDER BY 2 DESC;

-- Q.10 W.A SQL QUERY TO CREATE EACH SHIFT AND 
-- NUMBER OF ORDERS (EXAMPLE MORNING <= 12, AFTERNOON BETWEEN 12 AND 17, EVENING >17)
WITH Shift_Table AS(
	SELECT 
		*,
		CASE 
			WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'Morning'
			WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
			ELSE 'Evening'
		END AS SHIFT_LOG
	FROM RETAIL_SALES_DB
	)
SELECT 
	SHIFT_LOG,
	COUNT(*)
FROM Shift_Table
GROUP BY SHIFT_LOG;